site_name: "API DOCUMENTATION"
theme:
  name: material
nav:
  - Home: index.md
  - Project:
      - Intro: Introdution.md
      - Build it: Building.md
      - Requirements: requirements/train-ticket-machine-backend.pdf
      - How does it work?: How.md
  - Architecture:
      - System Architecture: System Architecture.md
      - Solution: "Solution Structure.md"
      - Layers:
          - API Layer: API Layer.md
          - Application Layer: Application Layer.md
          - Domain Layer: Domain Layer.md
          - Infrastructure Layer: Infrastructure Layer.md
          - Helper Modules: Modules.md
          - Implementation Details: Implementation Details.md
  - Testing:
      - Overview: Testing.md
      - Security: Security.md
      - Reports:
        - Coverage: coverage/index.html
        - Performance: Perf.md
  - Summary: Summary.md
extra_css:
  - css/custom.css
